//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightPoint.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int Id { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
