//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightPoint.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.Goods = new HashSet<Goods>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public System.TimeSpan WorkStartTime { get; set; }
        public System.TimeSpan WorkEndTime { get; set; }
    
        public virtual ICollection<Goods> Goods { get; set; }
    }
}
